services:
  - type: web
    name: chronos-planner-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_TIMEZONE
        value: Asia/Kolkata
      - key: TZ
        value: Asia/Kolkata
